package com.example.pocketloa.view.auction

enum class OptionEnum(val code : Int, val text: String) {

//	engraving
	RANCOR(118, "원한"),
	IRON_WILL(123, "굳은 의지"),
	SHIELD_PENETRATION(237, "실드 관통"),
	NECROMANCY(243, "강령술"),
	CURSED_DOLL(247, "저주받은 인형"),
	AWAKENING(255, "각성"),
	STABLE_STATE(111, "안정된 상태"),
	CRISIS_AVOIDANCE(140, "위기 모면"),
	MASTERFUL_POWER(238, "달인의 저력"),
	HEAVY_ARMOR(240, "중갑 착용"),
	REINFORCED_SHIELD(242, "강화 방패"),
	BROKEN_BONES(245, "부러진 뼈"),
	GAMBLER(248, "승부사"),
	PRICE_OF_SURPRISE(249, "기습의 대가"),
	FLOW_OF_MANA(251, "마나의 흐름"),
	WAR_CHIEF(254, "돌격대장"),
	IGNORING_THE_WEAK(107, "약자 무시"),
	ABSORBING_ENERGY(109, "정기 흡수"),
	ETHEREAL_PREDATOR(110, "에테르 포식자"),
	SUPER_CHARGE(121, "슈퍼 차지"),
	BEAD_MASTER(134, "구슬동자"),
	KEEN_MACE(141, "예리한 둔기"),
	INDOMITABLE(235, "불굴"),
	DIVINE_PROTECTION(239, "여신의 가호"),
	PREDESTINED_VICTORY(244, "선수필승"),
	PRECISE_STRIKE(142, "급소 타격"),
	CRUSHING_FIST(236, "분쇄의 주먹"),
	BOMB_EXPERT(241, "폭발물 전문가"),
	RAGE_OF_LIGHTNING(246, "번개의 분노"),
	BARRICADE(253, "바리케이드"),
	INCREASED_MANA_EFFICIENCY(168, "마나 효율 증가"),
	INCREASED_MAX_MANA(167, "최대 마나 증가"),
	MASTER_OF_ESCAPE(202, "탈출의 명수"),
	DUELIST(288, "결투의 대가"),
	MASS_INCREASE(295, "질량 증가"),
	PROPULSION(296, "추진력"),
	STRIKE_BONUS(297, "타격의 대가"),
	FOCUS(298, "시선 집중"),
	ADRENALINE(299, "아드레날린"),
	QUICK_RESOLUTION(300, "속전속결"),
	SPECIALIST(301, "전문의"),
	EMERGENCY_RESCUE(302, "긴급구조"),
	PRECISION_DAGGER(303, "정밀 단도"),
	FRENZY(125, "광기"),
	STRENGTHENING_WILL(127, "오의 강화"),
	WEAPON_ENHANCEMENT(129, "강화 무기"),
	FIREPOWER_ENHANCEMENT(130, "화력 강화"),
	WARRIOR_OF_LIGHTS_SECRET(188, "광전사의 비기"),
	INITIATIVE(189, "초심"),
	EXTREME_SKILLING(190, "극의: 체술"),
	SHOCK_TRAINING(191, "충격 단련"),
	MASTER_OF_KWANGKWA_PA_CHEON_MU(314, "권왕파천무"),
	SURA_PATH(315, "수라의 길"),
	GUNNER(192, "핸드거너"),
	BOMBARDMENT_ENHANCEMENT(193, "포격 강화"),
	TRUE_VALOR(194, "진실된 용맹"),
	URGENT_SALVATION(195, "절실한 구원"),
	IGNITION(293, "점화"),
	REFLUX(294, "환류"),
	HAMMERS_OF_WRATH(196, "분노의 망치"),
	GRAVITY_TRAINING(197, "중력 수련"),
	HIGH_LEVEL_SUMMONER(198, "상급 소환사"),
	OVERFLOWING_EMPATHY(199, "넘치는 교감"),
	EMPRESS_FAVOR(200, "황후의 은총"),
	EMPEROR_ORDERS(201, "황제의 칙령"),
	COMBAT_STANCE(224, "전투 태세"),
	LONELY_KNIGHT(225, "고독한 기사"),
	THREE_VEINS(256, "세맥타통"),
	OPPOSING_HEAVENS_AND_EARTH(257, "역천지체"),
	SECOND_COMPANION(258, "두 번째 동료"),
	ASSAULT_OF_DEATH(259, "죽음의 습격"),
	APEX(276, "절정"),
	RESTRAINT(277, "절제"),
	LINGERING_ENERGY(278, "잔재된 기운"),
	BURST(279, "버스트"),
	PERFECT_SUPPRESSION(280, "완벽한 억제"),
	UNSTOPPABLE_IMPULSE(281, "멈출 수 없는 충동"),
	JUDGE(282, "심판자"),
	BLESSING_AURA(283, "축복의 오라"),
	ARDETAIN_SKILL(284, "아르데타인의 기술"),
	HERITAGE_OF_EVOLUTION(285, "진화의 유산"),
	THIRST(286, "갈증"),
	MOON_SOUND(287, "달의 소리"),
	PEACEMAKER(289, "피스메이커"),
	HUNTING_TIME(290, "사냥의 시간"),
	ONE_SHOT_ONE_KILL(291, "일격필살"),
	CHAOS(292, "오의난무"),
	RETURN(305, "회귀"),
	BLOSSOM(306, "만개"),
	RAGING_TEMPEST(307, "질풍노도"),
	DEW(308, "이슬비"),
	PREDATOR(309, "포식자"),
	SLAYER(310, "처단자"),
	EXECUTOR_OF_MANWOL(311, "만월의 집행자"),
	LIMIT_BOUNDARY(312, "그믐의 경계"),

//	penalty
	ATTACK_REDUCTION(800, "공격력 감소"),
	ATTACK_SPEED_REDUCTION(802, "공격속도 감소"),
	DEFENSE_REDUCTION(801, "방어력 감소"),
	MOVEMENT_SPEED_REDUCTION(803, "이동속도 감소"),

//	stat
	LETHAL(15, "치명"),
	SPECIALIZATION(16, "특화"),
	SUPPRESSION(17, "제압"),
	SWIFTNESS(18, "신속"),
	PATIENCE(19, "인내"),
	PROFICIENCY(20, "숙련");

	companion object {
		// 주어진 텍스트에 해당하는 값 반환
		fun getcodeByText(text: String): Int? {
			return values().find { it.text == text }?.code
		}
	}
}